-- CreditFlow Automation v1
-- ADITIVE migration: does not delete existing data.

CREATE TABLE IF NOT EXISTS report_imports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  file_name TEXT,
  provider TEXT,
  report_date DATE,
  file_hash TEXT,
  item_count INTEGER NOT NULL DEFAULT 0,
  address_count INTEGER NOT NULL DEFAULT 0,
  score_count INTEGER NOT NULL DEFAULT 0,
  parser_status TEXT NOT NULL DEFAULT 'ok',
  parser_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_report_imports_client_date
  ON report_imports(client_id, report_date DESC, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_report_imports_client_hash
  ON report_imports(client_id, file_hash)
  WHERE file_hash IS NOT NULL;

CREATE TABLE IF NOT EXISTS removal_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  credit_item_id BIGINT NOT NULL REFERENCES credit_items(id) ON DELETE CASCADE,
  bureau TEXT,
  category TEXT NOT NULL,
  creditor_name TEXT,
  account_number TEXT,
  detected_report_id BIGINT REFERENCES report_imports(id) ON DELETE SET NULL,
  detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'confirmed',
  confidence NUMERIC(5,4) NOT NULL DEFAULT 1.0,
  amount NUMERIC(12,2),
  billing_status TEXT NOT NULL DEFAULT 'pendiente',
  notes TEXT,
  UNIQUE (credit_item_id, bureau)
);

CREATE INDEX IF NOT EXISTS idx_removal_events_client
  ON removal_events(client_id, detected_at DESC);

CREATE TABLE IF NOT EXISTS automation_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  event_status TEXT NOT NULL DEFAULT 'ok',
  detail TEXT,
  metadata_json TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_automation_events_client
  ON automation_events(client_id, created_at DESC);
