// CreditFlow v13.3 — ACE Mailing & Deadline Tracker
import v132 from "./index-v13-2.js";
import baseWorker from "./index.js";
import { createD1Shim } from "./db-shim.js";
const out=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
async function auth(req,env,ctx){const u=new URL(req.url);u.pathname="/api/auth/status";u.search="";const r=await baseWorker.fetch(new Request(u,{method:"GET",headers:req.headers}),env,ctx);if(!r.ok)return false;try{return !!(await r.json()).authenticated}catch{return false}}
const addDays=(d,n)=>new Date(new Date(d).getTime()+n*86400000).toISOString();
async function event(db,c,e,d,m={}){await db.prepare(`INSERT INTO aggressive_compliance_campaign_events(campaign_id,client_id,event_type,detail,metadata_json) VALUES(?,?,?,?,?)`).bind(c.id,c.client_id,e,d,JSON.stringify(m)).run()}
async function getOne(db,id,clientId){return db.prepare(`SELECT * FROM aggressive_compliance_campaigns WHERE id=? AND client_id=?`).bind(id,clientId).first()}
async function approve(db,c){if(c.status!=="draft")return {error:"Solo un borrador puede aprobarse.",status:409};await db.prepare(`UPDATE aggressive_compliance_campaigns SET status='approved',approved_at=NOW(),next_action='send_test',updated_at=NOW() WHERE id=?`).bind(c.id).run();await event(db,c,"approved","Campaña ACE aprobada para envío TEST.");return {ok:true}}
async function markDelivered(db,c,body){const delivered=body.delivered_at||new Date().toISOString();let standard=null,extended=null,mode="manual_review";if(c.target_type==="cra"){standard=addDays(delivered,30);extended=addDays(delivered,45);mode="cra_reinvestigation"}else if(c.target_type==="furnisher"){standard=addDays(delivered,30);extended=addDays(delivered,45);mode="furnisher_investigation"}else mode="collector_validation_rules";await db.prepare(`UPDATE aggressive_compliance_campaigns SET status='delivered',delivered_at=?,deadline_mode=?,standard_due_at=?,extended_due_at=?,deadline_status=?,next_action='wait_response',updated_at=NOW() WHERE id=?`).bind(delivered,mode,standard,extended,standard?"running":"manual_review",c.id).run();await event(db,c,"delivered","Entrega registrada; reloj aplicable evaluado.",{delivered_at:delivered,standard_due_at:standard,extended_due_at:extended,deadline_mode:mode});return {ok:true,delivered_at:delivered,standard_due_at:standard,extended_due_at:extended,deadline_mode:mode}}
async function response(db,c,body){const received=body.received_at||new Date().toISOString();await db.prepare(`INSERT INTO aggressive_compliance_responses(campaign_id,client_id,received_at,response_type,result,response_summary,metadata_json) VALUES(?,?,?,?,?,?,?)`).bind(c.id,c.client_id,received,body.response_type||"written",body.result||"received",body.response_summary||"",JSON.stringify(body.metadata||{})).run();await db.prepare(`UPDATE aggressive_compliance_campaigns SET status='responded',response_received_at=?,response_status=?,deadline_status='responded',next_action='analyze_response',updated_at=NOW() WHERE id=?`).bind(received,body.result||"received",c.id).run();await event(db,c,"response_received","Respuesta registrada para análisis.",{received_at:received,result:body.result||"received"});return {ok:true}}
async function deadlineReview(db,c,body){if(!c.delivered_at)return {error:"Primero registra la entrega real.",status:409};const now=new Date(),std=c.standard_due_at?new Date(c.standard_due_at):null,ext=c.extended_due_at?new Date(c.extended_due_at):null;let applicable=std,rationale="",potential=false,status="running";if(c.deadline_mode==="collector_validation_rules"){status="manual_review";rationale="Collector validation does not use the CRA 30-day deletion clock. Review timing and validation-notice facts.";applicable=null}else if(c.response_received_at){status="responded";rationale="A response is recorded. Analyze timeliness and substance before escalating."}else{const useExtended=!!body.extension_applies;applicable=useExtended&&ext?ext:std;if(applicable&&now>applicable){status="potential_failure";potential=true;rationale=`No response is recorded after the ${useExtended?"extended":"standard"} due date. Review the full facts before alleging noncompliance.`}else rationale=`Deadline is still running under the ${useExtended?"extended":"standard"} review setting.`}await db.prepare(`INSERT INTO aggressive_compliance_deadline_reviews(campaign_id,client_id,standard_due_at,extended_due_at,applicable_due_at,status,potential_failure,rationale,metadata_json) VALUES(?,?,?,?,?,?,?,?,?)`).bind(c.id,c.client_id,c.standard_due_at||null,c.extended_due_at||null,applicable?applicable.toISOString():null,status,potential,rationale,JSON.stringify({extension_applies:!!body.extension_applies})).run();await db.prepare(`UPDATE aggressive_compliance_campaigns SET deadline_status=?,deadline_extension_reason=?,escalation_status=?,next_action=?,updated_at=NOW() WHERE id=?`).bind(status,body.extension_reason||null,potential?"review_for_escalation":"not_ready",potential?"review_compliance_failure":(status==="responded"?"analyze_response":"wait_response"),c.id).run();return {ok:true,status,potential_failure:potential,rationale,applicable_due_at:applicable?applicable.toISOString():null}}
export default{async fetch(request,env,ctx){const u=new URL(request.url),m=request.method.toUpperCase();let hit=u.pathname.match(/^\/api\/aggressive-compliance\/client\/(\d+)\/campaigns\/(\d+)\/(approve|delivered|response|deadline-review)$/);if(hit&&m==="POST"){if(!(await auth(request,env,ctx)))return out({error:"No autorizado"},401);const db=createD1Shim(env),clientId=Number(hit[1]),id=Number(hit[2]),action=hit[3],c=await getOne(db,id,clientId);if(!c)return out({error:"Campaña no encontrada"},404);let body={};try{body=await request.json()}catch{};try{let r=action==="approve"?await approve(db,c):action==="delivered"?await markDelivered(db,c,body):action==="response"?await response(db,c,body):await deadlineReview(db,c,body);return out(r,r.error?(r.status||400):200)}catch(e){return out({error:"ACE v13.3 no pudo completar la acción",detail:String(e?.message||e)},500)}}return v132.fetch(request,env,ctx)}};
